config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :thietbis
  resources :loaithietbis
  resources :nhacungcaps
  resources :nhasanxuats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
end

app/models/nhasanxuat.rb
class Nhasanxuat < ApplicationRecord
    has_many :loaithietbis
end

app/controllers/nhasanxuats_controller.rb
class NhasanxuatsController < ApplicationController
  before_action :set_nhasanxuat, only: %i[ show edit update destroy ]

  # GET /nhasanxuats or /nhasanxuats.json
  def index
    @nhasanxuats = Nhasanxuat.all
  end

  # GET /nhasanxuats/1 or /nhasanxuats/1.json
  def show
  end

  # GET /nhasanxuats/new
  def new
    @nhasanxuat = Nhasanxuat.new
  end

  # GET /nhasanxuats/1/edit
  def edit
  end

  # POST /nhasanxuats or /nhasanxuats.json
  def create
    @nhasanxuat = Nhasanxuat.new(nhasanxuat_params)

    respond_to do |format|
      if @nhasanxuat.save
        format.html { redirect_to @nhasanxuat, notice: "Nhasanxuat was successfully created." }
        format.json { render :show, status: :created, location: @nhasanxuat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nhasanxuat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nhasanxuats/1 or /nhasanxuats/1.json
  def update
    respond_to do |format|
      if @nhasanxuat.update(nhasanxuat_params)
        format.html { redirect_to @nhasanxuat, notice: "Nhasanxuat was successfully updated." }
        format.json { render :show, status: :ok, location: @nhasanxuat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nhasanxuat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nhasanxuats/1 or /nhasanxuats/1.json
  def destroy
    @nhasanxuat.destroy
    respond_to do |format|
      format.html { redirect_to nhasanxuats_url, notice: "Nhasanxuat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nhasanxuat
      @nhasanxuat = Nhasanxuat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nhasanxuat_params
      params.require(:nhasanxuat).permit(:ten, :quocgia)
    end
end

app/helpers/nhasanxuats_helper.rb
module NhasanxuatsHelper
end

app/views/nhasanxuats/_form.html.erb
<%= form_with(model: nhasanxuat) do |form| %>
  <% if nhasanxuat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nhasanxuat.errors.count, "error") %> prohibited this nhasanxuat from being saved:</h2>

      <ul>
        <% nhasanxuat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ten %>
    <%= form.text_field :ten %>
  </div>

  <div class="field">
    <%= form.label :quocgia %>
    <%= form.text_field :quocgia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nhasanxuats/edit.html.erb
<h1>Editing Nhasanxuat</h1>
<%= render 'home/index'=%>

<%= render 'form', nhasanxuat: @nhasanxuat %>

<%= link_to 'Show', @nhasanxuat %> |
<%= link_to 'Back', nhasanxuats_path %>

app/views/nhasanxuats/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'home/index'=%>

<h1>Nhà sản xuất</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tên</th>
      <th>Quốc gia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nhasanxuats.each do |nhasanxuat| %>
      <tr>
        <td><%= nhasanxuat.ten %></td>
        <td><%= nhasanxuat.quocgia %></td>
        <td><button class ="btn btn-outline-success text-light"><%= link_to 'Show', nhasanxuat %></button></td>
        <td><button class ="btn btn-outline-primary text-light"><%= link_to 'Edit', edit_nhasanxuat_path(nhasanxuat) %></button></td>
        <td><button class ="btn btn-outline-danger text-light"><%= link_to 'Destroy', nhasanxuat, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class ="btn btn-outline-primary text-light"><%= link_to 'New Nhasanxuat', new_nhasanxuat_path %></button>

app/views/nhasanxuats/new.html.erb
<h1>New Nhasanxuat</h1>
<%= render 'home/index'=%>

<%= render 'form', nhasanxuat: @nhasanxuat %>

<%= link_to 'Back', nhasanxuats_path %>

app/views/nhasanxuats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ten:</strong>
  <%= @nhasanxuat.ten %>
</p>

<p>
  <strong>Quocgia:</strong>
  <%= @nhasanxuat.quocgia %>
</p>

<%= link_to 'Edit', edit_nhasanxuat_path(@nhasanxuat) %> |
<%= link_to 'Back', nhasanxuats_path %>