config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :thietbis
  resources :loaithietbis
  resources :nhacungcaps
  resources :nhasanxuats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
end

app/models/nhacungcap.rb
class Nhacungcap < ApplicationRecord
    has_many :loaithietbis
end

app/controllers/nhacungcaps_controller.rb
class NhacungcapsController < ApplicationController
  before_action :set_nhacungcap, only: %i[ show edit update destroy ]

  # GET /nhacungcaps or /nhacungcaps.json
  def index
    @nhacungcaps = Nhacungcap.all
  end

  # GET /nhacungcaps/1 or /nhacungcaps/1.json
  def show
  end

  # GET /nhacungcaps/new
  def new
    @nhacungcap = Nhacungcap.new
  end

  # GET /nhacungcaps/1/edit
  def edit
  end

  # POST /nhacungcaps or /nhacungcaps.json
  def create
    @nhacungcap = Nhacungcap.new(nhacungcap_params)

    respond_to do |format|
      if @nhacungcap.save
        format.html { redirect_to @nhacungcap, notice: "Nhacungcap was successfully created." }
        format.json { render :show, status: :created, location: @nhacungcap }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nhacungcap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nhacungcaps/1 or /nhacungcaps/1.json
  def update
    respond_to do |format|
      if @nhacungcap.update(nhacungcap_params)
        format.html { redirect_to @nhacungcap, notice: "Nhacungcap was successfully updated." }
        format.json { render :show, status: :ok, location: @nhacungcap }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nhacungcap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nhacungcaps/1 or /nhacungcaps/1.json
  def destroy
    @nhacungcap.destroy
    respond_to do |format|
      format.html { redirect_to nhacungcaps_url, notice: "Nhacungcap was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nhacungcap
      @nhacungcap = Nhacungcap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nhacungcap_params
      params.require(:nhacungcap).permit(:ten, :diachi, :sdt)
    end
end

app/helpers/nhacungcaps_helper.rb
module NhacungcapsHelper
end

app/views/nhacungcaps/_form.html.erb
<%= form_with(model: nhacungcap) do |form| %>
  <% if nhacungcap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nhacungcap.errors.count, "error") %> prohibited this nhacungcap from being saved:</h2>

      <ul>
        <% nhacungcap.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ten %>
    <%= form.text_field :ten %>
  </div>

  <div class="field">
    <%= form.label :diachi %>
    <%= form.text_field :diachi %>
  </div>

  <div class="field">
    <%= form.label :sdt %>
    <%= form.text_field :sdt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nhacungcaps/edit.html.erb
<h1>Editing Nhacungcap</h1>
<%= render 'home/index'=%>

<%= render 'form', nhacungcap: @nhacungcap %>

<%= link_to 'Show', @nhacungcap %> |
<%= link_to 'Back', nhacungcaps_path %>

app/views/nhacungcaps/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'home/index'=%>

<h1>Nhà Cung cấp</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Tên</th>
      <th>Địa chỉ</th>
      <th>SĐT</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nhacungcaps.each do |nhacungcap| %>
      <tr>
        <td><%= nhacungcap.ten %></td>
        <td><%= nhacungcap.diachi %></td>
        <td><%= nhacungcap.sdt %></td>
        <td><button class ="btn btn-outline-success text-light"><%= link_to 'Show', nhacungcap %></button></td>
        <td><button class ="btn btn-outline-primary text-light"><%= link_to 'Edit', edit_nhacungcap_path(nhacungcap) %></button></td>
        <td><button class ="btn btn-outline-danger text-light"><%= link_to 'Destroy', nhacungcap, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class ="btn btn-outline-success text-light"><%= link_to 'New Nhacungcap', new_nhacungcap_path %></button>

app/views/nhacungcaps/new.html.erb
<h1>New Nhacungcap</h1>
<%= render 'home/index'=%>

<%= render 'form', nhacungcap: @nhacungcap %>

<%= link_to 'Back', nhacungcaps_path %>

app/views/nhacungcaps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ten:</strong>
  <%= @nhacungcap.ten %>
</p>

<p>
  <strong>Diachi:</strong>
  <%= @nhacungcap.diachi %>
</p>

<p>
  <strong>Sdt:</strong>
  <%= @nhacungcap.sdt %>
</p>

<%= link_to 'Edit', edit_nhacungcap_path(@nhacungcap) %> |
<%= link_to 'Back', nhacungcaps_path %>