config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :thietbis
  resources :loaithietbis
  resources :nhacungcaps
  resources :nhasanxuats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
end

app/models/thietbi.rb
class Thietbi < ApplicationRecord
  belongs_to :nhasanxuat
  belongs_to :loaithietbi
  belongs_to :nhacungcap
end

app/controllers/thietbis_controller.rb
class ThietbisController < ApplicationController
  before_action :set_thietbi, only: %i[ show edit update destroy ]

  # GET /thietbis or /thietbis.json
  def index
    @thietbis = Thietbi.all
  end

  # GET /thietbis/1 or /thietbis/1.json
  def show
  end

  # GET /thietbis/new
  def new
    @thietbi = Thietbi.new
  end

  # GET /thietbis/1/edit
  def edit
  end

  # POST /thietbis or /thietbis.json
  def create
    @thietbi = Thietbi.new(thietbi_params)

    respond_to do |format|
      if @thietbi.save
        format.html { redirect_to @thietbi, notice: "Thietbi was successfully created." }
        format.json { render :show, status: :created, location: @thietbi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thietbi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thietbis/1 or /thietbis/1.json
  def update
    respond_to do |format|
      if @thietbi.update(thietbi_params)
        format.html { redirect_to @thietbi, notice: "Thietbi was successfully updated." }
        format.json { render :show, status: :ok, location: @thietbi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thietbi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thietbis/1 or /thietbis/1.json
  def destroy
    @thietbi.destroy
    respond_to do |format|
      format.html { redirect_to thietbis_url, notice: "Thietbi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thietbi
      @thietbi = Thietbi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thietbi_params
      params.require(:thietbi).permit(:tenthietbi, :nhasanxuat_id, :thongsokt, :loaithietbi_id, :nhacungcap_id)
    end
end

app/helpers/thietbis_helper.rb
module ThietbisHelper
end

app/views/thietbis/_form.html.erb
<%= form_with(model: thietbi) do |form| %>
  <% if thietbi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thietbi.errors.count, "error") %> prohibited this thietbi from being saved:</h2>

      <ul>
        <% thietbi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tenthietbi %>
    <%= form.text_field :tenthietbi %>
  </div>

  <div class="field">
    <%= form.label :nhasanxuat_id %>
    <%= form.collection_select(:nhasanxuat_id, Nhasanxuat.all, :id, :ten, prompt: true) =%>
  </div>

  <div class="field">
    <%= form.label :thongsokt %>
    <%= form.text_field :thongsokt %>
  </div>

  <div class="field">
    <%= form.label :loaithietbi_id %>
    <%= form.collection_select(:loaithietbi_id, Loaithietbi.all, :id, :tenloai, prompt: true) =%>
  </div>

  <div class="field">
    <%= form.label :nhacungcap_id %>
    <%= form.collection_select(:nhacungcap_id, Nhacungcap.all, :id, :ten, prompt: true) =%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thietbis/edit.html.erb
<h1>Editing Thietbi</h1>
<%= render 'home/index'=%>

<%= render 'form', thietbi: @thietbi %>

<%= link_to 'Show', @thietbi %> |
<%= link_to 'Back', thietbis_path %>

app/views/thietbis/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'home/index'=%>

<h1>Thiết bị</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Tên thiết bị</th>
      <th>Nhà sản xuất</th>
      <th>Thông số kĩ thuật</th>
      <th>Loại thiết bị</th>
      <th>Nhà cung cấp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thietbis.each do |thietbi| %>
      <tr>
        <td><%= thietbi.tenthietbi %></td>
        <td><%= thietbi.nhasanxuat.ten %></td>
        <td><%= thietbi.thongsokt %></td>
        <td><%= thietbi.loaithietbi.tenloai %></td>
        <td><%= thietbi.nhacungcap.ten %></td>
        <td><button class ="btn btn-outline-success text-light"><%= link_to 'Show', thietbi %></button></td>
        <td><button class ="btn btn-outline-primary text-light"><%= link_to 'Edit', edit_thietbi_path(thietbi) %></button></td>
        <td><button class ="btn btn-outline-danger text-light"><%= link_to 'Destroy', thietbi, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<span class = "btn btn-outline-primary"><%= link_to 'New Thietbi', new_thietbi_path %></span>

app/views/thietbis/new.html.erb
<%= render 'home/index'=%>
<h1>New Thietbi</h1>

<%= render 'form', thietbi: @thietbi %>

<%= link_to 'Back', thietbis_path %>

app/views/thietbis/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Tenthietbi:</strong>
  <%= @thietbi.tenthietbi %>
</p>

<p>
  <strong>Nhasanxuat:</strong>
  <%= @thietbi.nhasanxuat_id %>
</p>

<p>
  <strong>Thongsokt:</strong>
  <%= @thietbi.thongsokt %>
</p>

<p>
  <strong>Loaithietbi:</strong>
  <%= @thietbi.loaithietbi_id %>
</p>

<p>
  <strong>Nhacungcap:</strong>
  <%= @thietbi.nhacungcap_id %>
</p>

<%= link_to 'Edit', edit_thietbi_path(@thietbi) %> |
<%= link_to 'Back', thietbis_path %>