config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :thietbis
  resources :loaithietbis
  resources :nhacungcaps
  resources :nhasanxuats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
end

app/models/loaithietbi.rb
class Loaithietbi < ApplicationRecord
    has_many :loaithietbis
end

app/controllers/loaithietbis_controller.rb
class LoaithietbisController < ApplicationController
  before_action :set_loaithietbi, only: %i[ show edit update destroy ]

  # GET /loaithietbis or /loaithietbis.json
  def index
    @loaithietbis = Loaithietbi.all
  end

  # GET /loaithietbis/1 or /loaithietbis/1.json
  def show
  end

  # GET /loaithietbis/new
  def new
    @loaithietbi = Loaithietbi.new
  end

  # GET /loaithietbis/1/edit
  def edit
  end

  # POST /loaithietbis or /loaithietbis.json
  def create
    @loaithietbi = Loaithietbi.new(loaithietbi_params)

    respond_to do |format|
      if @loaithietbi.save
        format.html { redirect_to @loaithietbi, notice: "Loaithietbi was successfully created." }
        format.json { render :show, status: :created, location: @loaithietbi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loaithietbi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loaithietbis/1 or /loaithietbis/1.json
  def update
    respond_to do |format|
      if @loaithietbi.update(loaithietbi_params)
        format.html { redirect_to @loaithietbi, notice: "Loaithietbi was successfully updated." }
        format.json { render :show, status: :ok, location: @loaithietbi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loaithietbi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loaithietbis/1 or /loaithietbis/1.json
  def destroy
    @loaithietbi.destroy
    respond_to do |format|
      format.html { redirect_to loaithietbis_url, notice: "Loaithietbi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loaithietbi
      @loaithietbi = Loaithietbi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loaithietbi_params
      params.require(:loaithietbi).permit(:tenloai, :donvitinh, :ghichu)
    end
end

app/helpers/loaithietbis_helper.rb
module LoaithietbisHelper
end

app/views/loaithietbis/_form.html.erb
<%= form_with(model: loaithietbi) do |form| %>
  <% if loaithietbi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loaithietbi.errors.count, "error") %> prohibited this loaithietbi from being saved:</h2>

      <ul>
        <% loaithietbi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tenloai %>
    <%= form.text_field :tenloai %>
  </div>

  <div class="field">
    <%= form.label :donvitinh %>
    <%= form.text_field :donvitinh %>
  </div>

  <div class="field">
    <%= form.label :ghichu %>
    <%= form.text_field :ghichu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loaithietbis/edit.html.erb
<h1>Editing Loaithietbi</h1>
<%= render 'home/index'=%>

<%= render 'form', loaithietbi: @loaithietbi %>

<%= link_to 'Show', @loaithietbi %> |
<%= link_to 'Back', loaithietbis_path %>

app/views/loaithietbis/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'home/index'=%>

<h1>Loại thiết bị</h1>

<table class = "table">
  <thead>
    <tr>
      <th>Tên</th>
      <th>Đơn vị tính</th>
      <th>Ghi chú</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loaithietbis.each do |loaithietbi| %>
      <tr>
        <td><%= loaithietbi.tenloai %></td>
        <td><%= loaithietbi.donvitinh %></td>
        <td><%= loaithietbi.ghichu %></td>
        <td><button class ="btn btn-outline-success text-light"><%= link_to 'Show', loaithietbi %></button></td>
        <td><button class ="btn btn-outline-primary text-light"><%= link_to 'Edit', edit_loaithietbi_path(loaithietbi) %></button></td>
        <td><button class ="btn btn-outline-danger text-light"><%= link_to 'Destroy', loaithietbi, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class ="btn btn-outline-primary text-light"><%= link_to 'New Loaithietbi', new_loaithietbi_path %></button>

app/views/loaithietbis/new.html.erb
<h1>New Loaithietbi</h1>
<%= render 'home/index'=%>

<%= render 'form', loaithietbi: @loaithietbi %>

<%= link_to 'Back', loaithietbis_path %>

app/views/loaithietbis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tenloai:</strong>
  <%= @loaithietbi.tenloai %>
</p>

<p>
  <strong>Donvitinh:</strong>
  <%= @loaithietbi.donvitinh %>
</p>

<p>
  <strong>Ghichu:</strong>
  <%= @loaithietbi.ghichu %>
</p>

<%= link_to 'Edit', edit_loaithietbi_path(@loaithietbi) %> |
<%= link_to 'Back', loaithietbis_path %>